# Generated by Django 3.1 on 2020-08-24 23:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('is_pets_allowed', models.BooleanField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.TextField(max_length=300)),
                ('weekly_discount', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('monthly_discount', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Special_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='airpnp.listing')),
            ],
            options={
                'unique_together': {('listing', 'date')},
            },
        ),
    ]
